# docker-compose up -d --build
version: "2.4"
x-net: &net
  networks:
      - main
services:
  screener:
    build: .
    image: screener:v0.0.0
    environment:
      - JUPYTER_DISPLAY_FILEPATH=/home/dja/notebooks/github_screener.ipynb
    user: 1000:anaconda
    # entrypoint: ["/bin/sh"]
    # command:
    #   - -c
    #   - >
    #     echo hey;
    #     tail -f /dev/null;
    ports:
      - "8888:8888"
    volumes:
      - ./notebook:/home/dja/notebooks
      - ./jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py
    <<: *net
networks:
  main: